services:
  fgta5:
    container_name: fgta5
    image: webserver_8_4
    hostname: fgta5
    ports:
      - 8006:80
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CONFIG=config-development.php
      - DEBUG=true
    volumes:
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./webserver.conf:/etc/apache2/sites-available/webserver.conf
      - ./../:/home/agung/Development/fgta5/framework:consistent
      - ./../../../agungdhewe/webservice:/home/agung/Development/agungdhewe/webservice:consistent
    working_dir: /home/agung/Development/fgta5/framework

networks:
  devnetwork:
    name: devnetwork
    external: true




