<?php declare(strict_types=1);
	define('__TEMPLATE_NAME__', 'containertemplate');

	use AgungDhewe\Webservice\Session;
	use Fgta5\Framework\TemplateContainer;
	
	$tpl = TemplateContainer::getObject($this);
	$user = Session::GetWebUser();

	

?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<link rel="icon" href="/favicon.ico">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
		
		<?=$tpl->getBlockContent('header-metadata')?>
	
		<style>
		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-style.css']); ?>
		</style>	
		<?=$tpl->getBlockContent('header-style')?>

		<script>
		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-header-script.js']); ?>
		</script>

		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'fgta5component.inc.phtml']); ?>

		<?=$tpl->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			head
		</header>


		<main>
			<?=$tpl->getMainContent()?>
		</main>

		<nav id="container-nav">
			menu
		</nav>

		<?php
			require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-loading-mask.html']);
		?>
	</body>	


	<script>
		<?php
			require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-footer-script.js']);
		?>
	</script>
	<?=$tpl->getBlockContent('footer-script')?>

</html>