<?php
	define('__TEMPLATE_NAME__', 'container');

	use AgungDhewe\Webservice\Session;
	use Fgta5\Framework\TemplateContainer;
	
	$tpl = TemplateContainer::getTemplate($this);
	$user = Session::GetUser();

?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="<?=$tpl->GetTemplateAssetUrl('assets/style.css')?>">
		<?=$tpl->getBlockContent('header-metadata')?>
		<?=$tpl->getBlockContent('header-style')?>
		<script>
			var $ui = {};
		</script>
		<?=$tpl->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			<h1>Ini Container Template</h1>
		</header>
		<main>
			<?=$tpl->getMainContent()?>
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>
	</body>	
	<?=$tpl->getBlockContent('footer-script')?>
</body>