<?php declare(strict_types=1);
	define('__TEMPLATE_NAME__', 'containertemplate');

	use AgungDhewe\Webservice\Session;
	use Fgta5\Framework\TemplateContainer;
	
	$tpl = TemplateContainer::getObject($this);
	$user = Session::GetUser();

?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<link rel="icon" href="/favicon.ico">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="asset/assets/style.css">
		<link rel="stylesheet" href="<?=$tpl->GetTemplateAssetUrl('assets/containerlayout.css')?>">
		<?=$tpl->getBlockContent('header-metadata')?>
	
		<style>
			.hidden {
				display: none !important;
			}
		</style>	

		<?=$tpl->getBlockContent('header-style')?>
		
		<script>
			var $ui = {};
		</script>
		<?=$tpl->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			head
		</header>


		<main>
			<?=$tpl->getMainContent()?>
		</main>

		<nav id="container-nav">
			menu
		</nav>

		<div id="container-pagemask" style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; display: flex; justify-content: center; align-items: center; background-color: #fff;">
			<div>
			Please Wait ...
			</div>
		</div>
	</body>	
	<?=$tpl->getBlockContent('footer-script')?>

	<script>
		window.addEventListener("load", async (event) => {
			var pagemask = document.getElementById('container-pagemask')
			pagemask.classList.add('hidden');
			// body.style.opacity = 1;
		});
	</script>	
</body>