<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->getTitle()?></title>
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="<?=$this->getAssetUrl('assets/style.css')?>">
		<?=$this->getBlockContent('header-metadata')?>
		<?=$this->getBlockContent('header-style')?>
		<script>
			var $ui = {};
		</script>
		<?=$this->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			<h1>Ini Module Template</h1>
			<nav></nav>
		</header>
		<main>
			<?=$this->getMainContent()?>
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>
	</body>
	<?=$this->getBlockContent('footer-script')?>
</body>