<?php declare(strict_types=1);
	define('__TEMPLATE_NAME__', 'moduletemplate');

	use AgungDhewe\Webservice\Session;
	use Fgta5\Framework\TemplateModule;
	
	$tpl = TemplateModule::getObject($this);
	$user = Session::GetWebUser();

?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<link rel="icon" href="/favicon.ico">
		
		<?=$tpl->getBlockContent('header-metadata')?>

		<style>
		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-style.css']); ?>
		</style>	
		<?=$tpl->getBlockContent('header-style')?>


		<script>
		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-header-script.js']); ?>
		</script>

		<?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'fgta5component.inc.phtml']); ?>

		<?=$tpl->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			<h1>Ini Module Template</h1>
			<nav></nav>
		</header>
		<main>
			<?=$tpl->getMainContent()?>
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>


		<?php
			require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-loading-mask.html']);
		?>
	</body>

	<script>
		<?php
			require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'basic-footer-script.js']);
		?>
	</script>
	<?=$tpl->getBlockContent('footer-script')?>
	

</html>