<?php declare(strict_types=1);
	define('__TEMPLATE_NAME__', 'pagetemplate');

	use AgungDhewe\Webservice\Session;
	use Fgta5\Framework\TemplatePage;
	
	$tpl = TemplatePage::getObject($this);
	$user = Session::GetUser();

?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="asset/assets/style.css">
		<?=$tpl->getBlockContent('header-metadata')?>
		<?=$tpl->getBlockContent('header-style')?>
		<?=$tpl->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			<h1>Kalista</h1>
		</header>
		<main>
			<?=$tpl->getMainContent()?>
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>
	</body>
	<?=$tpl->getBlockContent('footer-script')?>
</body>